- src/core/config.js
- src/core/player/actions.js
This patch creates two **for** loops that search through all the NPCs and Items on the map. If one is clicked then the colour of the context menu is changed to support this in action.js.
In config.js the colour of the options can be set.
This was patch was made to resolve issue #17.
Motivation was created by #17. I see that it completely resolves the issue.
Checking all NPCs and Items available to click as well as checking pre-patch functionality with post-patch to ensure that no errors were made and nothing important was accidentally removed.
> Content Menu Colours

- server/core/npc.js
- server/core/player.js
- src/main.js
When an NPC moves, it will look in the correct `array` in the `tileWalkable` method (Should probably change this.) in the `UI` class by applying the parameter `layer` to the `foreground` so it knows which `array` to look from.
This closes #25 
An NPC should not be allowed to talk into blocked tiles in the foreground layer.
> Fix the NPC movement in blocked foreground tiles.

- src/Navarra.vue
- src/components/ui/Login.vue
- src/main.js
Added a cancelLogin method to the Navarra.vue file.
Using the pre-existing event bus in the login.vue file, I put an event listener in the 'created' hook of the Navarra.vue lifecycle. It calls on the cancelLogin method, which sets the screen to 'main'.
[Issue #28 Cancel button on login screen should back to main screen](https://github.com/Navarra/game/issues/28)
The user needs to be able to return to the main screen if, let's say, they clicked on the login button by accident and need to register. Refreshing the page is never a good solution.
- Went to login screen
- Clicked 'cancel'
- Was returned to main screen
Also logged in, logged out, and clicked 'cancel' again. Did not see any exceptions thrown in Chrome or Firefox consoles.
> Added cancel button functionality to Login Screen

- src/Delaford.vue
Added a `ref` to the `Slots` component for easy access to the `selected` property. On logout, set the slot's selected value back to 1 (inventory tab).
https://github.com/delaford/game/issues/47
Game dev is fun! Reason enough if you ask me. 😁
Also fixes an issue.
1. Log in
2. Switch tabs
3. Log out
4. Log in
> Fix bug: reset tab to 'Inventory' on logout

- server/core/context-menu.js
- server/player/handlers/actions/index.js
- src/components/GameCanvas.vue
- src/components/sub/ContextMenu.vue
- src/components/util/ItemGrid.vue
When you hover over the game map or anywhere an action can take place, you will see the first action available in the top-left and the # of available options. You will also be able to quickly left-click to perform that action.
This is a point-and-click game.
> Add the top action from context-menu as first left-click on the top-left of game

- src/Delaford.vue
- src/components/ui/Login.vue
#64 Fixed issue - Preventing duel login 
https://github.com/delaford/game/issues/64
This fix prevents someone who is clicking the login button twice quickly (or tapping the enter key multiple time on a relevant field) from login more than once.
Manual Q&A only. Attempted to double click / double press enter and watch the console for the number of logins . Prior to the fix you would get more than one.
> issue #64 - You can login twice via fast-clicking the login form - Fixed

- .gitignore
- package.json
Fixed #74 - updated the v-for syntax, added _id field to player.json skills and removed the capitalizing method in favor of css text-transform. The skill stats should now show up well and produce no errors in the console.
https://github.com/delaford/game/issues/74
Stats tab was not showing well,
Manual testing only: click the stats tab and see the skills. open the console and see no errors.
I had to use "eslint-disable-line" for two lines in the css of the "skill-name" class. I'm not sure why is this failing the commit script, but it otherwise fails at "npm run lint:css".
> Fixing issue #74 - No skill stats showing in pane & console TypeError

- src/Delaford.vue
- src/components/game-panes/Bank.vue
Added a `bus` event listener to handle tab changes - `bus.$on('show-sidebar', tabNumber)`. This should make any other future tab changes easier to handle as well.
In this case specifically, when the bank is displayed (the component is `mounted`), it emits an event with the inventory slot number.
https://github.com/delaford/game/issues/60
Manual testing - click on any tab other than inventory, click on the bank gnome
> Fix bug: change tab to inventory when banking

- server/core/functions/shop.js
- src/Delaford.vue
Made the Chatbox component load conditionally upon the game world opening. This cleared up the old text.
This was accomplished by changing this.screen to 'game' at the end of the game world loading instructions.
https://github.com/delaford/game/issues/46
Creates a fresh experience for the user on each log in.
I added text to the chat window, both player chat and system notifications, and then logged out and back in.
> Chatbox component now reloads when game world is loaded

- server/core/functions/shop.js
Inside the `shop.js` file, the coins were being added to the inventory when there were no coins already there and the item was taken afterwards. This created the effect of the coins taking up the second available slot when the player held no coins in their inventory.
#96 
The previous behavior of buying and selling was awkward and unnatural to the user experience.
This was a very isolated instance of code, therefore, there should be no affect on other areas as the change was minimal. Going into the game and testing with the shopkeeper showed intended effects, coins were placed into the inventory in the first available slot and the item was successfully sold.
> Switched the order in which items are taken/placed into inventory in shop

- server/core/data/items/general.js
- server/core/functions/shop.js
When an item is attempted to be sold, check for the presence of a `prohibited` attribute on the item and if false, prevent the sale. Added `prohibited` with the value of `false` to the coins item. Removed unused `untradeable` attribute on the coins item.
Fixes #95 
Prevents the player from losing their coins.
> Check prohibited attribute on items when selling

- server/core/functions/shop.js
When checking the value of coins, it will now display the coins quantity (value) instead of false.
#99 
The coins would display a false value when inspecting it's value.
> Fixed the coin value to display it's actual value.

- server/core/functions/shop.js
Update coinIndex on a shop instance after removing a sold item from inventory to accurately be able to reference the coins slot later in the code.
Fixes #101 
Fixes crash
> When an item is sold, update the index where coins are in inventory

- server/core/functions/shop.js
Instead of attempting to show a price for prohibited items and showing a price of 0 (or false as in #99), show a witty sentence instead.
Fixes #99 
Clarifies to the player that this type of item cannot be sold and doesn't display a nonsensical value of false.
> Show a message instead of a price when valuing prohibited items

- src/components/GameCanvas.vue
Emit the ```screen:close``` event when the user click on the map
Fix #94 
Enhancement
> Fix issue #94 - 'Popup screen does not close when moving away'

- package.json
Rewrote npm script using npm packages that enable cross-platform support.
#73 
Enables devs on every platform to be able to contribute to the project.
Tested on Ubuntu 19.04 and Windows 10 Pro
I couldn't get the ndb command to work on windows. For me it only works with a global installation of ndb and manually typing `ndb npm run dev:node`. On Linux, it works just fine.
> Fix issue #73 - Change npm scripts to be cross-platform

- server/player/handlers/socket-events/index.js
- server/socket.js
- src/core/map.js
I made a validation on socket event when verifying players valid based on player and viewport x,y and pass those players to the broadcast event.
#27 
This resolve chat local issue,  before, all users connected will see the sent message, now just the players inside the sender viewport can do that.
> Change socket to recognize current viewport and filter players on that

- server/player/action.js
- server/player/handlers/actions/index.js
I made the action be immediate (not queueable) if the player click himself on the center of the viewport
I add some validation on action pane (bank, furnace, anvil, smelt and trade) cause data.playerIndex is not send as a parameter when the action is not queueable.
#119 
This fixes the bug when you are on top of an NPC and want to trade/shop/bank with them and the popup screen will not popup UNTIL you move and FINISH its progress.
> Fix Bug Trading/Banking on NPC while ON TOP causes delay

- server/core/player.js
- server/shared/ui.js
Fix level of skill experience progress, changes made:
* Added a routine to check skill levels in the player builder
* Removed the "zero" skill level, the minimum level will always be 1
* Adjusted the level formula for level 2 starts at 73 experience and level 99 around 11 million exp.
#153 
The skill level was not being checked on the player constructor, so this could lead to the level of the skill being different from the real experience value
> Fix levels of progress

- server/core/skills/smithing.js
- server/player/handlers/actions/index.js
Bug fix for issue #151
The function smithing.forge() now returns a bool that details if the forge was successful, this bool is then used to block experience updates if the smithing attempt was unsuccessful.
[ You get smithing EXP even if you have no bars #151 ](https://github.com/delaford/game/issues/151)
Players can't spam experience while trying to forge an item that they're unable to forge.
Attempted to craft a bronze mace with only 4 bars in inventory, checking total experience before and after the act of forging.
> Bug fix: Player can't spam experience while smithing

- src/core/map.js
Dropped items graphic now reflects the quantity. Code has been added to the drawItems() function in Map so that the proper tile column is selected for the appropriate quantity amount.
Players now have immediate feedback for how much of a given quantity the player will receive upon taking an item.
[ Stacked quantity does not reflect on game map #115 ](https://github.com/delaford/game/issues/115)
Bug fix/extension of an existing feature.
Just dropped coins of varying quantities around the map (see below).
> Image quantity fixed on dropped items
